import Image from "next/image";
import Link from "next/link";
import { Icons } from "../icons";

export function ImgGallery({
  images,
  skeletonCount,
}: {
  images: string[];
  skeletonCount: number;
}) {
  const imgArray = Array.from({ length: skeletonCount }, (_, i) => i);

  return (
    <div className="grid min-h-[75vh] grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
      {imgArray.map((_, i) => (
        <ImageSkeleton key={i} />
      ))}
      {images.map((img, i) => (
        <div key={i} className="group relative h-fit w-fit ">
          <div className="absolute inset-0 hidden rounded-lg bg-black/50 group-hover:block">
            <Link
              {...{ target: "_blank", rel: "noopener noreferrer" }}
              href={img}
              className="absolute inset-0 flex items-center justify-center gap-5 text-2xl font-bold text-white underline"
            >
              <Icons.download className="h-8 w-8" fill="white" />
              Download
            </Link>
          </div>
          <Image
            alt="image generated by openai from prompt"
            src={img}
            width={400}
            height={400}
            placeholder="blur"
            blurDataURL={rgbDataURL(107, 114, 128)}
            className="rounded-lg"
          />
        </div>
      ))}
    </div>
  );
}

export function ImageSkeleton() {
  return (
    <div className="h-64 w-full animate-pulse rounded-lg bg-gray-500"></div>
  );
}

// Pixel GIF code adapted from https://stackoverflow.com/a/33919020/266535
const keyStr =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";

const triplet = (e1: number, e2: number, e3: number) =>
  keyStr.charAt(e1 >> 2) +
  keyStr.charAt(((e1 & 3) << 4) | (e2 >> 4)) +
  keyStr.charAt(((e2 & 15) << 2) | (e3 >> 6)) +
  keyStr.charAt(e3 & 63);

const rgbDataURL = (r: number, g: number, b: number) =>
  `data:image/gif;base64,R0lGODlhAQABAPAA${
    triplet(0, r, g) + triplet(b, 255, 255)
  }/yH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==`;
