import Image from "next/image";
import Link from "next/link";
import { Icons } from "../icons";
import { useState } from "react";

const getUrlToDownloadImage = (imgUrl: string) => {
  return `/api/download_from_bucket/${encodeURIComponent(imgUrl)}`;
};

export function ImgGallery({
  images,
  skeletonCount,
}: {
  images: string[];
  skeletonCount: number;
}) {
  const imgArray = Array.from({ length: skeletonCount }, (_, i) => i);
  const defaultImgListWithStatus = images.map((img) => ({
    url: img,
    loaded: false,
  }));
  const [imgListWithStatus, setImgListWithStatus] = useState(
    defaultImgListWithStatus
  );

  return (
    <div className="grid  grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
      {imgArray.map((_, i) => (
        <ImageSkeleton key={i} />
      ))}
      {images.map((img, i) => (
        <div key={i} className="group relative h-fit w-fit ">
          <div className="absolute inset-0 hidden rounded-lg bg-black/50 group-hover:block">
            <Link
              download={"image"}
              href={`${getUrlToDownloadImage(img)}`}
              className="absolute inset-0 flex items-center justify-center gap-5 text-2xl font-bold text-white underline"
            >
              <Icons.download className="h-8 w-8" fill="white" />
              Download
            </Link>
          </div>
          <Image
            alt="image generated by openai from prompt"
            src={img}
            width={400}
            height={400}
            className="rounded-lg"
          />
        </div>
      ))}
    </div>
  );
}

export function ImageSkeleton() {
  return (
    <div className="aspect-square w-full animate-pulse rounded-lg bg-gray-500"></div>
  );
}
