import Image from "next/image";
import Link from "next/link";
import { Icons } from "../icons";
import { cn } from "@/utils/class-merge";
import { type Dispatch, type SetStateAction } from "react";

const getUrlToDownloadImage = (imgUrl: string) => {
  return `/api/download_from_bucket/${encodeURIComponent(imgUrl)}`;
};
export type ImageWithStatus = { url: string; loaded: boolean };

export function ImgGallery({
  images,
  setImagesWithStatus,
}: {
  images: ImageWithStatus[];
  setImagesWithStatus: Dispatch<SetStateAction<ImageWithStatus[]>>;
}) {
  const handleChangeImgLoadingStatus = (index: number) => {
    setImagesWithStatus((prev) =>
      prev.map((img, i) => {
        if (index === i) return { ...img, loaded: true };
        return img;
      })
    );
  };

  console.log("gallery", images);
  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
      {images.map((img, i) => (
        <div key={i} className="group relative h-fit w-fit ">
          {img.loaded && <DownloadLayer imgUrl={img.url} />}
          {!img.loaded && <ImageSkeleton />}
          {img.url && (
            <Image
              alt="image generated by openai from prompt"
              src={img.url}
              width={400}
              height={400}
              priority
              className={cn("rounded-lg", { hidden: !img.loaded })}
              onLoadingComplete={() => handleChangeImgLoadingStatus(i)}
            />
          )}
        </div>
      ))}
    </div>
  );
}

export function DownloadLayer({ imgUrl }: { imgUrl: string }) {
  return (
    <div className="absolute inset-0 hidden rounded-lg bg-black/50 group-hover:block">
      <Link
        download={"image"}
        href={`${getUrlToDownloadImage(imgUrl)}`}
        className="absolute inset-0 flex items-center justify-center gap-5 text-2xl font-bold text-white underline"
      >
        <Icons.download className="h-8 w-8" fill="white" />
        Download
      </Link>
    </div>
  );
}
export function ImageSkeleton() {
  return (
    <div className="aspect-square w-[324px] animate-pulse rounded-lg bg-gray-500"></div>
  );
}
